dist: MagoKimbra

language: c

sudo: true

cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

notifications:
  email:
    on_success: true
    on_failure: false

before_install:
  # Fetch the tag information for the current branch
  - git fetch origin --tags
  - source ${TRAVIS_BUILD_DIR}/install.sh

before_script:
  # Change current working directory to the build dir
  - cd ${TRAVIS_BUILD_DIR}

script:

  # Backup Configuration pins_RAMPS.h
  - cp MK4duo/Configuration_Basic.h         MK4duo/Configuration_Basic.h.backup
  - cp MK4duo/Configuration_Cartesian.h     MK4duo/Configuration_Cartesian.h.backup
  - cp MK4duo/Configuration_Core.h          MK4duo/Configuration_Core.h.backup
  - cp MK4duo/Configuration_Delta.h         MK4duo/Configuration_Delta.h.backup
  - cp MK4duo/Configuration_Feature.h       MK4duo/Configuration_Feature.h.backup
  - cp MK4duo/Configuration_LCD.h           MK4duo/Configuration_LCD.h.backup
  - cp MK4duo/Configuration_Motor_Driver.h  MK4duo/Configuration_Motor_Driver.h.backup
  - cp MK4duo/Configuration_Temperature.h   MK4duo/Configuration_Temperature.h.backup

  # Build with the default configurations
  - build_mk4duo

  # Test 2 extruders and heated bed on basic RAMPS 1.4
  # Test a "Fix Mounted" Probe with Safe Homing
  # Display REPRAP_DISCOUNT_SMART_CONTROLLER, sdsupport, eeprom
  - opt_set_basic MOTHERBOARD BOARD_RAMPS_13_HHB
  - opt_set_basic EXTRUDERS 2
  - opt_set_basic POWER_SUPPLY 1
  - opt_set_temp TEMP_SENSOR_HE0 20
  - opt_set_temp TEMP_SENSOR_HE1 1
  - opt_set_temp TEMP_SENSOR_BED0 1
  - opt_set_temp PIDTEMPBED true
  - opt_enable_cartesian Z_PROBE_FIX_MOUNTED Z_SAFE_HOMING
  - opt_enable_lcd REPRAP_DISCOUNT_SMART_CONTROLLER
  - opt_enable_feature SDSUPPORT EEPROM_SETTINGS
  - build_mk4duo
  
  - restore_configs
